Experiment_name: embeddings_w_labels_27_2
output_name: joint_embeddings.pt

# feeder
feeder: feeders.feeder.Feeder
feeder_args:
  data_path: /work/cvcs2024/SLR_sentiment_enhanced/SLRSE_model_data/SL-GCN/sign/27/train_data_joint.npy
  label_path: /work/cvcs2024/SLR_sentiment_enhanced/SLRSE_model_data/SL-GCN/sign/27/train_label.pkl
  random_mirror: False
  normalization: True
  is_vector: True

# model
model: model.decouple_gcn_attn.Model
model_args:
  num_class: 2000
  num_point: 27
  num_person: 1
  graph: graph.sign_27.Graph
  groups: 16
  block_size: 41
  graph_args:
    labeling_mode: "spatial"

#optim
weight_decay: 0.0001
base_lr: 0.01
step: [50]

# training
device: 0
weights: /work/cvcs2024/SLR_sentiment_enhanced/model_weights/SL-GCN/New_check_point/1/sign_joint_final-249.pt
keep_rate: 0.9
batch_size: 1
nesterov: True
warm_up_epoch: 0

# retrival
embeddings: /work/cvcs2024/SLR_sentiment_enhanced/SLRSE_model_data/Retrival/Embeddings/embeddings_w_labels_27_2/joint_embeddings.pt
target_file: /work/cvcs2024/SLR_sentiment_enhanced/SLRSE_model_data/SL-GCN/sign/27/val_data_joint.npy
label_file: /work/cvcs2024/SLR_sentiment_enhanced/SLRSE_model_data/SL-GCN/sign/27/val_label.pkl
out_folder: /work/cvcs2024/SLR_sentiment_enhanced/SLRSE_model_data/Ensemble/Retrival/joint
part: val
